  return <VStack gap={6}><PageHeader title="Hasabatlar" description="Sene aralygy boýunça jemlenen görkezijiler." action={<Button label="CSV eksport demo" variant="secondary" onClick={() => {const csv = ['ID,Müşderi,Hyzmat,Ýagdaý,Baha', ...orders.map((item) => [item.id, item.client, item.service, item.status, item.price].join(','))].join('\n'); const blob = new Blob([csv], {type: 'text/csv'}); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'nexa-orders.csv'; a.click(); URL.revokeObjectURL(url);}} />} /><Card padding={5}><DateRangeInput label="Hasabat seneleriniň aralygy" value={range} onChange={setRange} presets={[{label: 'Soňky 7 gün', getRange: () => ({start: '2026-07-10', end: '2026-07-16'})}, {label: 'Şu aý', getRange: () => ({start: '2026-07-01', end: '2026-07-31'})}]} /></Card><TabList value={tab} onChange={setTab} hasDivider><Tab value="summary" label="Jemleme" /><Tab value="services" label="Hyzmatlar" /><Tab value="details" label="Maglumat" /></TabList>{tab === 'summary' && <Grid columns={{minWidth: 220, repeat: 'fit'}} gap={4}><StatCard label="Sargyt sany" value={String(orders.length)} note={range ? `${range.start} — ${range.end}` : 'Ähli döwür'} badge="Live" /><StatCard label="Müşderi sany" value={String(clients.length)} note="Ýerli maglumatlar" badge="+1" /><StatCard label="Tamamlanan" value={String(orders.filter((item) => item.status === 'Taýýar').length)} note="Taýýar işler" badge="Kadaly" /></Grid>}{tab === 'services' && <Card padding={5}><VStack gap={4}><ProgressBar label="Web we landing" value={78} hasValueLabel variant="success" /><ProgressBar label="Admin paneller" value={62} hasValueLabel variant="accent" /><ProgressBar label="Mobil prototip" value={41} hasValueLabel variant="warning" /></VStack></Card>}{tab === 'details' && <Card padding={5}><MetadataList columns="single"><MetadataListItem label="Sene aralygy">{range ? `${range.start} — ${range.end}` : 'Saýlanmady'}</MetadataListItem><MetadataListItem label="Maglumat çeşmesi">LocalStorage demo maglumatlary</MetadataListItem><MetadataListItem label="Eksport">CSV işleýär</MetadataListItem><MetadataListItem label="Backend">Goşulmady</MetadataListItem></MetadataList></Card>}</VStack>;
}

function ActivityPage({activities}: {activities: Activity[]}) {
  return <VStack gap={6}><PageHeader title="Işleriň taryhy" description="Kim näme üýtgetdi diýen audit görnüşiniň frontend demosydyr." /><Card padding={5}><VStack gap={3}>{activities.map((item) => <Card key={item.id} padding={4}><HStack justify="between" gap={4}><HStack gap={3}><Badge variant={item.kind === 'success' ? 'success' : item.kind === 'warning' ? 'warning' : 'info'} label={item.kind === 'success' ? 'Üstünlik' : item.kind === 'warning' ? 'Üýtgeşme' : 'Maglumat'} /><Text>{item.text}</Text></HStack><Text type="supporting" color="secondary">{item.time}</Text></HStack></Card>)}</VStack></Card></VStack>;
}

function SettingsPage({compact, setCompact, mode, setMode, onReset}: {compact: boolean; setCompact: (value: boolean) => void; mode: 'light' | 'dark'; setMode: (value: 'light' | 'dark') => void; onReset: () => void}) {
  return <VStack gap={6}><PageHeader title="Sazlamalar" description="Tema we tablisa görnüşleri LocalStorage-da saklanýar." /><Grid columns={{minWidth: 320, repeat: 'fit'}} gap={4}><Card padding={5}><VStack gap={4}><Heading level={2} type="display-3">Görnüş</Heading><Switch label="Garaňky režim" value={mode === 'dark'} onChange={(value) => setMode(value ? 'dark' : 'light')} labelSpacing="spread" width="100%" /><Switch label="Ykjam tablisa" value={compact} onChange={setCompact} labelSpacing="spread" width="100%" /></VStack></Card><Card padding={5}><VStack gap={4}><Heading level={2} type="display-3">Ýerli maglumatlar</Heading><Text color="secondary">Sargytlar, müşderiler, tema we iş taryhy brauzeriň LocalStorage ulgamynda saklanýar.</Text><Button label="Ýerli maglumatlary arassala" variant="secondary" onClick={onReset} /></VStack></Card></Grid></VStack>;
}

function OrderDetailDialog({order, onClose, onStatus}: {order: Order | null; onClose: () => void; onStatus: (status: OrderStatus) => void}) {
  const [tab, setTab] = useState('overview');
  useEffect(() => setTab('overview'), [order?.id]);
  return <Dialog isOpen={Boolean(order)} onOpenChange={(open) => !open && onClose()} width={620}><Layout header={<DialogHeader title={order ? `${order.id} · ${order.service}` : 'Sargyt'} onOpenChange={(open) => !open && onClose()} />} content={<LayoutContent>{order && <VStack gap={5}><TabList value={tab} onChange={setTab} hasDivider><Tab value="overview" label="Jemleme" /><Tab value="client" label="Müşderi" /><Tab value="history" label="Taryh" /></TabList>{tab === 'overview' && <MetadataList columns="single"><MetadataListItem label="Ýagdaý"><Badge variant={statusVariant(order.status)} label={order.status} /></MetadataListItem><MetadataListItem label="Bahasy">{order.price}</MetadataListItem><MetadataListItem label="Sene">{order.date}</MetadataListItem><MetadataListItem label="Düşündiriş">{order.description}</MetadataListItem></MetadataList>}{tab === 'client' && <Card padding={5}><VStack gap={2}><Heading level={3}>{order.client}</Heading><Text color="secondary">Bu ýerde müşderiniň sargyt bilen bagly çalt maglumatlary görkezilýär.</Text></VStack></Card>}{tab === 'history' && <Banner status="info" title="Sargyt taryhy" description="Soňky status üýtgeşmeleri Iş taryhy bölüminde ýazylýar." />}</VStack>}</LayoutContent>} footer={<LayoutFooter hasDivider><HStack justify="between" gap={2}><DropdownMenu button={{label: 'Ýagdaýy üýtget', variant: 'secondary'}} items={[{label: 'Taýýar', onClick: () => onStatus('Taýýar')}, {label: 'Işlenýär', onClick: () => onStatus('Işlenýär')}, {label: 'Garaşylýar', onClick: () => onStatus('Garaşylýar')}]} /><Button label="Ýap" variant="primary" onClick={onClose} /></HStack></LayoutFooter>} /></Dialog>;
}

function ClientProfileDialog({client, orders, onClose}: {client: Client | null; orders: Order[]; onClose: () => void}) {
  const [tab, setTab] = useState('profile');
  useEffect(() => setTab('profile'), [client?.id]);
  const clientOrders = client ? orders.filter((item) => item.client === client.name) : [];
  return <Dialog isOpen={Boolean(client)} onOpenChange={(open) => !open && onClose()} width={680}><Layout header={<DialogHeader title={client ? client.name : 'Müşderi'} subtitle="Müşderiniň aýratyn profili" onOpenChange={(open) => !open && onClose()} />} content={<LayoutContent>{client && <VStack gap={5}><HStack gap={4} align="center"><Avatar name={client.name} size={64} /><VStack gap={1}><Heading level={2} type="display-3">{client.name}</Heading><Badge variant={statusVariant(client.status)} label={client.status} /></VStack></HStack><TabList value={tab} onChange={setTab} hasDivider><Tab value="profile" label="Profil" /><Tab value="orders" label="Sargytlar" endContent={<Badge variant="info" label={String(clientOrders.length)} />} /><Tab value="notes" label="Bellikler" /></TabList>{tab === 'profile' && <MetadataList columns="single"><MetadataListItem label="E-poçta">{client.email}</MetadataListItem><MetadataListItem label="Telefon">{client.phone}</MetadataListItem><MetadataListItem label="Jemi sargyt">{client.orders}</MetadataListItem><MetadataListItem label="Jemi töleg">{client.total}</MetadataListItem></MetadataList>}{tab === 'orders' && (clientOrders.length ? <VStack gap={2}>{clientOrders.map((item) => <Card key={item.id} padding={4}><HStack justify="between"><VStack gap={1}><Text weight="bold">{item.service}</Text><Text type="supporting" color="secondary">{item.id} · {item.date}</Text></VStack><Badge variant={statusVariant(item.status)} label={item.status} /></HStack></Card>)}</VStack> : <EmptyState title="Sargyt tapylmady" description="Bu müşderiniň demo sargydy ýok." />)}{tab === 'notes' && <Card padding={5}><Text>{client.notes}</Text></Card>}</VStack>}</LayoutContent>} footer={<LayoutFooter hasDivider><HStack justify="end"><Button label="Ýap" variant="primary" onClick={onClose} /></HStack></LayoutFooter>} /></Dialog>;
}
